# makefile for postfix operator project (HW #5)
# Author: David J DeBonis
# Version: 2020-09-30

# ************************************
# variables to control op

CXX = g++ -std=c++11
# CXXFLAGS = -Wall -g

# *************************************
# targets

main: main.cpp
	$(CXX) main.cpp
clean:
	rm *.out
	echo Removed output file(s)
	rm postfix.txt
	echo Removed postfix.txt file
